--------------------------------------------------------
--  Arquivo criado - terça-feira-outubro-28-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_T_SGF_CATEGORIA
--------------------------------------------------------

   CREATE SEQUENCE  "RM000000"."SEQ_T_SGF_CATEGORIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_T_SGF_LOCAL
--------------------------------------------------------

   CREATE SEQUENCE  "RM000000"."SEQ_T_SGF_LOCAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_T_SGF_META
--------------------------------------------------------

   CREATE SEQUENCE  "RM000000"."SEQ_T_SGF_META"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_T_SGF_RECORRENCIA
--------------------------------------------------------

   CREATE SEQUENCE  "RM000000"."SEQ_T_SGF_RECORRENCIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_T_SGF_RESUMO_MENSAL
--------------------------------------------------------

   CREATE SEQUENCE  "RM000000"."SEQ_T_SGF_RESUMO_MENSAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_T_SGF_TRANSACAO
--------------------------------------------------------

   CREATE SEQUENCE  "RM000000"."SEQ_T_SGF_TRANSACAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_T_SGF_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "RM000000"."SEQ_T_SGF_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table T_SGF_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "RM000000"."T_SGF_CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"NM_CATEGORIA" VARCHAR2(50 BYTE), 
	"TIPO_CATEGORIA" VARCHAR2(30 BYTE), 
	"ICONE_CATEGORIA" VARCHAR2(30 BYTE), 
	"COR_HEX" VARCHAR2(7 BYTE), 
	"IS_PADRAO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SGF_LOCAL
--------------------------------------------------------

  CREATE TABLE "RM000000"."T_SGF_LOCAL" 
   (	"ID_LOCAL" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"NM_LOCAL" VARCHAR2(100 BYTE), 
	"TIPO_LOCAL" CHAR(1 BYTE), 
	"DS_ENDERECO" VARCHAR2(200 BYTE), 
	"DS_CORDENADAS" VARCHAR2(100 BYTE), 
	"DT_ULTIMO_USO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SGF_META
--------------------------------------------------------

  CREATE TABLE "RM000000"."T_SGF_META" 
   (	"ID_META" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_CATEGORIA" NUMBER(*,0), 
	"TITULO_META" VARCHAR2(100 BYTE), 
	"DS_META" VARCHAR2(255 BYTE), 
	"VL_ALVO" NUMBER(10,2), 
	"VL_ATUAL" NUMBER(10,2), 
	"DT_INICIO" DATE, 
	"DT_LIMITE" DATE, 
	"TIPO_META" CHAR(1 BYTE), 
	"NOTIFICACAO_CONFIG" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" 
 LOB ("NOTIFICACAO_CONFIG") STORE AS SECUREFILE (
  TABLESPACE "TBSPC_ALUNOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_SGF_RECORRENCIA
--------------------------------------------------------

  CREATE TABLE "RM000000"."T_SGF_RECORRENCIA" 
   (	"ID_RECORRENCIA" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_CATEGORIA" NUMBER(*,0), 
	"ID_LOCAL" NUMBER(*,0), 
	"TITULO_RECORRENCIA" VARCHAR2(50 BYTE), 
	"DS_RECORRENCIA" VARCHAR2(100 BYTE), 
	"VL_RECORRENTE" NUMBER(10,2), 
	"TIPO_RECORRENCIA" VARCHAR2(20 BYTE), 
	"FREQ_RECORRENCIA" CHAR(1 BYTE), 
	"DT_REFERENCIA" DATE, 
	"TOTAL_OCORRENCIAS" NUMBER(*,0), 
	"OCORRENCIAS_RESTANTES" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SGF_RESUMO_MENSAL
--------------------------------------------------------

  CREATE TABLE "RM000000"."T_SGF_RESUMO_MENSAL" 
   (	"ID_RESUMO" NUMBER(*,0), 
	"REF_MES" VARCHAR2(7 BYTE), 
	"TOTAL_ENTRADAS" NUMBER(10,2), 
	"TOTAL_SAIDAS" NUMBER(10,2), 
	"DS_CATEGORIAS" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" 
 LOB ("DS_CATEGORIAS") STORE AS SECUREFILE (
  TABLESPACE "TBSPC_ALUNOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "RM000000"."T_SGF_RESUMO_MENSAL"."REF_MES" IS '01/2025 = Example';
--------------------------------------------------------
--  DDL for Table T_SGF_TRANSACAO
--------------------------------------------------------

  CREATE TABLE "RM000000"."T_SGF_TRANSACAO" 
   (	"ID_TRANSACAO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_CATEGORIA" NUMBER(*,0), 
	"ID_RECORRENCIA" NUMBER(*,0), 
	"ID_LOCAL" NUMBER(*,0), 
	"VL_TRANSACAO" NUMBER(10,2), 
	"DT_TRANSICAO" DATE, 
	"DS_TRANSACAO" VARCHAR2(150 BYTE), 
	"TIPO_TRANSACAO" CHAR(1 BYTE), 
	"PARCELA_TRANSACAO" NUMBER(*,0), 
	"TOTAL_PARCELAS" NUMBER(*,0), 
	"IS_RECORRENTE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SGF_USUARIO
--------------------------------------------------------

  CREATE TABLE "RM000000"."T_SGF_USUARIO" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"NM_USUARIO" VARCHAR2(100 BYTE), 
	"EMAIL_USUARIO" VARCHAR2(100 BYTE), 
	"SENHA_HASH" VARCHAR2(255 BYTE), 
	"DT_CADASTRO" DATE, 
	"DT_ULTIMO_LOGIN" DATE, 
	"PREF_USUARIO" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" 
 LOB ("PREF_USUARIO") STORE AS SECUREFILE (
  TABLESPACE "TBSPC_ALUNOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into RM000000.T_SGF_CATEGORIA
SET DEFINE OFF;
REM INSERTING into RM000000.T_SGF_LOCAL
SET DEFINE OFF;
REM INSERTING into RM000000.T_SGF_META
SET DEFINE OFF;
REM INSERTING into RM000000.T_SGF_RECORRENCIA
SET DEFINE OFF;
REM INSERTING into RM000000.T_SGF_RESUMO_MENSAL
SET DEFINE OFF;
REM INSERTING into RM000000.T_SGF_TRANSACAO
SET DEFINE OFF;
REM INSERTING into RM000000.T_SGF_USUARIO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index T_SGF_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_USUARIO_PK" ON "RM000000"."T_SGF_USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_RECORRENCIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_RECORRENCIA_PK" ON "RM000000"."T_SGF_RECORRENCIA" ("ID_RECORRENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_TRANSACAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_TRANSACAO_PK" ON "RM000000"."T_SGF_TRANSACAO" ("ID_TRANSACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_RECORRENCIA_TITULO_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_RECORRENCIA_TITULO_UN" ON "RM000000"."T_SGF_RECORRENCIA" ("TITULO_RECORRENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_RESUMO_MENSAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_RESUMO_MENSAL_PK" ON "RM000000"."T_SGF_RESUMO_MENSAL" ("ID_RESUMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_META_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_META_PK" ON "RM000000"."T_SGF_META" ("ID_META") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_LOCAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_LOCAL_PK" ON "RM000000"."T_SGF_LOCAL" ("ID_LOCAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_CATEGORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_CATEGORIA_PK" ON "RM000000"."T_SGF_CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_CATEGORIA_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_CATEGORIA_UK" ON "RM000000"."T_SGF_CATEGORIA" ("NM_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_META_TITULO_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_META_TITULO_UN" ON "RM000000"."T_SGF_META" ("TITULO_META") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_LOCAL_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_LOCAL_UK" ON "RM000000"."T_SGF_LOCAL" ("NM_LOCAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index T_SGF_USUARIO_EMAIL_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM000000"."T_SGF_USUARIO_EMAIL_UN" ON "RM000000"."T_SGF_USUARIO" ("EMAIL_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table T_SGF_META
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_META" MODIFY ("ID_META" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_META" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_META" MODIFY ("TITULO_META" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_META" MODIFY ("VL_ALVO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_META" MODIFY ("VL_ATUAL" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_META" MODIFY ("DT_INICIO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_META" MODIFY ("DT_LIMITE" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_META" MODIFY ("TIPO_META" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_META" ADD CONSTRAINT "T_SGF_META_ATUAL_CK" CHECK (vl_atual >= 0) ENABLE;
  ALTER TABLE "RM000000"."T_SGF_META" ADD CONSTRAINT "T_SGF_META_PK" PRIMARY KEY ("ID_META")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM000000"."T_SGF_META" ADD CONSTRAINT "T_SGF_META_TIPO_CK" CHECK (tipo_meta IN ('E', 'G', 'L')) ENABLE;
  ALTER TABLE "RM000000"."T_SGF_META" ADD CONSTRAINT "T_SGF_META_TITULO_UN" UNIQUE ("TITULO_META")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM000000"."T_SGF_META" ADD CONSTRAINT "T_SGF_META_VALOR_CK" CHECK (vl_alvo > vl_atual) ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SGF_USUARIO
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_USUARIO" MODIFY ("NM_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_USUARIO" MODIFY ("EMAIL_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_USUARIO" MODIFY ("SENHA_HASH" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_USUARIO" MODIFY ("DT_CADASTRO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_USUARIO" ADD CONSTRAINT "T_SGF_USUARIO_EMAIL_UN" UNIQUE ("EMAIL_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM000000"."T_SGF_USUARIO" ADD CONSTRAINT "T_SGF_USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SGF_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_CATEGORIA" MODIFY ("NM_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_CATEGORIA" MODIFY ("TIPO_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_CATEGORIA" MODIFY ("IS_PADRAO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_CATEGORIA" ADD CONSTRAINT "T_SGF_CATEGORIA_PK" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM000000"."T_SGF_CATEGORIA" ADD CONSTRAINT "T_SGF_CATEGORIA_UK" UNIQUE ("NM_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SGF_LOCAL
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_LOCAL" MODIFY ("ID_LOCAL" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_LOCAL" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_LOCAL" MODIFY ("NM_LOCAL" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_LOCAL" MODIFY ("TIPO_LOCAL" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_LOCAL" ADD CONSTRAINT "T_SGF_LOCAL_PK" PRIMARY KEY ("ID_LOCAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM000000"."T_SGF_LOCAL" ADD CONSTRAINT "T_SGF_LOCAL_TIPO" CHECK (tipo_local IN ('F', 'O')) ENABLE;
  ALTER TABLE "RM000000"."T_SGF_LOCAL" ADD CONSTRAINT "T_SGF_LOCAL_UK" UNIQUE ("NM_LOCAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SGF_RESUMO_MENSAL
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_RESUMO_MENSAL" MODIFY ("ID_RESUMO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_RESUMO_MENSAL" MODIFY ("REF_MES" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_RESUMO_MENSAL" MODIFY ("TOTAL_ENTRADAS" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_RESUMO_MENSAL" MODIFY ("TOTAL_SAIDAS" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_RESUMO_MENSAL" ADD CONSTRAINT "T_SGF_RESUMO_MENSAL_PK" PRIMARY KEY ("ID_RESUMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SGF_RECORRENCIA
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" MODIFY ("ID_RECORRENCIA" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" MODIFY ("TITULO_RECORRENCIA" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" MODIFY ("VL_RECORRENTE" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" MODIFY ("TIPO_RECORRENCIA" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" MODIFY ("FREQ_RECORRENCIA" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" ADD CONSTRAINT "T_SGF_RECORRENCIA_FREQ_CK" CHECK (freq_recorrencia IN ('D', 'W', 'M', 'Y' )) ENABLE;
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" ADD CONSTRAINT "T_SGF_RECORRENCIA_PK" PRIMARY KEY ("ID_RECORRENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" ADD CONSTRAINT "T_SGF_RECORRENCIA_TIPO_CK" CHECK (tipo_recorrencia IN ('F', 'P')) DISABLE;
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" ADD CONSTRAINT "T_SGF_RECORRENCIA_TITULO_UN" UNIQUE ("TITULO_RECORRENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SGF_TRANSACAO
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" MODIFY ("ID_TRANSACAO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" MODIFY ("VL_TRANSACAO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" MODIFY ("DT_TRANSICAO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" MODIFY ("TIPO_TRANSACAO" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" MODIFY ("IS_RECORRENTE" NOT NULL ENABLE);
  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" ADD CONSTRAINT "T_SGF_TRANSACAO_PK" PRIMARY KEY ("ID_TRANSACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_SGF_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_CATEGORIA" ADD CONSTRAINT "FK_CAT_USU" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "RM000000"."T_SGF_USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_SGF_LOCAL
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_LOCAL" ADD CONSTRAINT "FK_LOC_USU" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "RM000000"."T_SGF_USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_SGF_META
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_META" ADD CONSTRAINT "FK_META_CAT" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "RM000000"."T_SGF_CATEGORIA" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "RM000000"."T_SGF_META" ADD CONSTRAINT "FK_META_USU" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "RM000000"."T_SGF_USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_SGF_RECORRENCIA
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" ADD CONSTRAINT "FK_REC_CAT" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "RM000000"."T_SGF_CATEGORIA" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" ADD CONSTRAINT "FK_REC_LOC" FOREIGN KEY ("ID_LOCAL")
	  REFERENCES "RM000000"."T_SGF_LOCAL" ("ID_LOCAL") ENABLE;
  ALTER TABLE "RM000000"."T_SGF_RECORRENCIA" ADD CONSTRAINT "FK_REC_USU" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "RM000000"."T_SGF_USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_SGF_TRANSACAO
--------------------------------------------------------

  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" ADD CONSTRAINT "FK_TRA_CAT" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "RM000000"."T_SGF_CATEGORIA" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" ADD CONSTRAINT "FK_TRA_LOC" FOREIGN KEY ("ID_LOCAL")
	  REFERENCES "RM000000"."T_SGF_LOCAL" ("ID_LOCAL") ENABLE;
  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" ADD CONSTRAINT "FK_TRA_REC" FOREIGN KEY ("ID_RECORRENCIA")
	  REFERENCES "RM000000"."T_SGF_RECORRENCIA" ("ID_RECORRENCIA") ENABLE;
  ALTER TABLE "RM000000"."T_SGF_TRANSACAO" ADD CONSTRAINT "FK_TRA_USU" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "RM000000"."T_SGF_USUARIO" ("ID_USUARIO") ENABLE;
